---

- name: Configure Kafka integration
  template:
    dest: /etc/newrelic-infra/integrations.d/kafka-config.yml
    src: kafka-config.yml.j2
  vars:
    instances: "{{ sansible_newrelic_integration_kafka_instances_default
      | combine(sansible_newrelic_integration_kafka_instances) }}"
