---

- name: Converge
  hosts: all

  pre_tasks:
    - name: Install
      become: yes
      apt:
        pkg: gnupg
        state: present

  roles:
    - role: sansible.newrelic_integration_infra
      sansible_newrelic_integration_infra_apt_repo_keyserver: https://keyserver.ubuntu.com
      sansible_newrelic_integration_infra_version: "1.*"
      sansible_newrelic_integration_infra_settings:
        license_key: 123456789123456789123456789123456789
        custom_attributes:
          org: sansible
          role: newrelic

    - role: newrelic_integration_kafka
      sansible_newrelic_integration_kafka_labels:
        lorem: ipsum
        dolor: sit ament
      sansible_newrelic_integration_kafka_zookeeper_hosts:
        - host: zookeeper.localhost
          port: 2181
      sansible_newrelic_integration_kafka_zookeeper_path: /test/path
      sansible_newrelic_integration_kafka_bootstrap_broker_host: bootstrap.localhost

      sansible_newrelic_integration_kafka_instances:
        - name: metric-zookeeper-bootstrap
          command: metrics
          arguments:
            cluster_name: test_zookeeper
            autodiscover_strategy: zookeeper
            default_jmx_port: 1234
        - name: metric-zookeeper-bootstrap-override
          command: metrics
          arguments:
            cluster_name: test_zookeeper
            autodiscover_strategy: zookeeper
            zookeeper_path: /test/path/override
        - name: metric-broker-bootstrap
          command: metrics
          arguments:
            cluster_name: test_bootstrap
            autodiscover_strategy: 'bootstrap'
            default_jmx_port: 1234
        - name: kafka-producer
          command: consumer_offset
          arguments:
            cluster_name: test_cluster
            producers: '[]'
