---

- name: Converge
  hosts: all

  roles:
    - role: sansible.newrelic_integration_infra
      sansible_newrelic_integration_infra_settings:
        license_key: 123456789123456789123456789123456789
        custom_attributes:
          org: sansible
          role: newrelic

    - role: newrelic_integration_kafka
      sansible_newrelic_integration_kafka_zookeeper_hosts:
        - host: zookeeper1.localnet
          port: 2181
      sansible_newrelic_integration_kafka_instances:
        kafka-metrics:
          arguments:
            default_jmx_port: 1234
